### PR TITLE
CO-2885 Merger les communications rules avec le module support

### PR DESCRIPTION
**Pull request by SylvainLosey**
La migration et l'envoi de mail à l'air de fonctionner correctement mais à controller

### CODE REVIEW

**Comment by ecino** [comment]
@josueBulle Can you review the code please?

**Comment by josueBulle** [comment]
I think there is an issue with the revision module. Or I don't remember how to use variables in the template.
Just to be sure: when we reply to a `crm.request`, we can only choose a template, not a config. Is it how it is supposed to be ?

(Also, I'm not sure if it's relevant but maybe the `partner.communication.config` generated by the migration script should be defined in xml. So that when we install modules creating `mail.templates` but don't run this very specific migration, the related configs still exist)

**Comment by SylvainLosey** [comment]
> Just to be sure: when we reply to a `crm.request`, we can only choose a template, not a config. Is it how it is supposed to be ?

Yes, when replying to a `crm.request` the interface / functionnality is the same. This PR is meant to facilitate changes to support `email.template` by allowing them to be modified by their corresponding `partner.communication.config`

**Review by eicher31 — APPROVED** [review]
Looks good to me!

**Pull request merged**
