### PR TITLE
Import letters improvements

### PR DESCRIPTION
**Pull request by ecino**
- Reduce disk writes
- Allow multiple letters in single document : cut by barcodes

### CODE REVIEW

**Comment by ecino** [comment]
@MickSandoz Can you quickly review the code to check nothing bad is hidden in this big pull request?

**Comment by ecino** [comment]
Then you will be able to rebase on this...

**Comment by MickSandoz** [comment]
I checked, and I think it's OK like this

**Comment by ecino** [comment]
Ok, thank you

**Pull request merged**
