### PR TITLE
CO-386 Fix demand planning CRON

### PR DESCRIPTION
**Pull request by maxime-beck**

### CODE REVIEW

**Comment by ecino** [comment]
You should as well correct method `_get_default_weekly_demands()` because it creates prevision for next week, but it should be for the week after.

**Comment by maxime-beck** [comment]
Doesn't `_get_default_weekly_demands()` creates/updates the previsions for all the weeks after the current one ?
https://github.com/maxime-beck/compassion-modules/blob/master/crm_compassion/models/demand_planning.py#L54

**Comment by ecino** [comment]
Yes this is good but it starts from next sunday instead of sunday in two weeks :
https://github.com/maxime-beck/compassion-modules/blob/master/crm_compassion/models/demand_planning.py#L51

**Comment by ecino** [comment]
:+1:

**Pull request merged**
