### PR TITLE
T1574 - Fix contact parent (2/2)

### PR DESCRIPTION
**Pull request by Prazn**
follow-up of [PR](https://github.com/CompassionCH/compassion-switzerland/pull/1652)

### CODE REVIEW

**Review by ecino — COMMENTED** [review]
Why not having this change also in `partner_compassion` module? I don't see the point of having this in `partner_communication`, it is totally unrelated in my opinion.

**Comment by Prazn** [comment]
> Why not having this change also in `partner_compassion` module? I don't see the point of having this in `partner_communication`, it is totally unrelated in my opinion.

I agree that it makes sense to do it in `partner_compassion`. What I'm still not sure is should I still do it here since we are fixing something that comes from the base `contacts` module ? Because if let's say we decide not to use the module `partner_compassion`, we would not have this fix anymore.

**Comment by ecino** [comment]
Yes please.

**Comment by Prazn** [comment]
> Yes please.

Alright, published new PR - https://github.com/CompassionCH/compassion-switzerland/pull/1660

**Pull request closed without merging**
